### ISSUE TITLE
v2 beta 2.0.3:  strapi-server.js: Unexpected token '.'  Error: could not load js config file.

### ISSUE THREAD

**Issue by fletchzone** [VirtusLab-Open-Source/strapi-plugin-navigation#134] opened 2022-01-10 14:14 UTC
v2 beta: 2.0.3: This error occurs on yarn strapi dev.  Not on yarn strap build.    I looked at strapi-server.js and it looks fine...no errors.

Angular CLI: 12.0.5
Node: 12.22.8
Package Manager: npm 6.14.15
OS: win32 x64

![image](https://user-images.githubusercontent.com/7855564/148779527-fbf78b44-7dd2-43d2-a23b-5ee789182c3b.png)

**Comment by cyp3rius** [comment] 2022-01-10 14:20
@fletchzone  thanks for raising the issue. By your configuration I see you're using really old node and npm versions. That's indeed the total minimum which strapi is advicing but we recommend node v14 because of security reasons.

Anyway let us check the issue, I guess the `require` handling by this node version is the reason of it.

**Comment by cyp3rius** [comment] 2022-01-21 14:02
@fletchzone the issue is simply with `?.` usage in our node.js codebase. This is supported by node `v14`. Version `v12` which you're using is going to end support by May 2022 (in 4 months according to https://nodejs.org/en/about/releases/). Are you considering to switch to `v14`? Providing even temp backward compatibility is going to be significant effort for us.

**Comment by cyp3rius** [comment] 2022-01-27 07:46
Closing.

**Closed by cyp3rius** 2022-01-27 07:46 UTC
Labels: bug, v4, waiting for feedback
