### ISSUE TITLE
Single types still can't be enabled in general settings with v2.0.10

### ISSUE THREAD

**Issue by Nabellaleen** [VirtusLab-Open-Source/strapi-plugin-navigation#192] opened 2022-03-30 09:48 UTC
On my test server, I've only 2 singles types : `landing-page` and `landingpage`
They have no inter-type relations.

When I try do add one or both in the `Enable for collection(s)` parameter then save, the parameter is not saved and then the types are not displayed in the `UI Navigation / New item` popup

![Peek 30-03-2022 11-45](https://user-images.githubusercontent.com/3717607/160802938-44b0f9dd-f515-4c2c-afe8-a4dced9e8677.gif)

The PUT network request is the following (response 200) :
```
{"contentTypes":["api::landing-page.landing-page","api::landingpage.landingpage"],"contentTypesNameFields":{"default":["title","subject","name"]},"contentTypesPopulate":{},"additionalFields":[],"allowedLevels":2,"gql":{"navigationItemRelated":["LandingPage","Landingpage"]}}
```

The GET immediately made after the PUT return the following (so with an empty content types array) :
```
{"contentTypes":[],"contentTypesNameFields":{"default":["title","subject","name"]},"contentTypesPopulate":{},"allowedLevels":2,"additionalFields":[],"isGQLPluginEnabled":false}
```

My env' :
```
    "@strapi/plugin-i18n": "4.1.5",
    "@strapi/plugin-users-permissions": "4.1.5",
    "@strapi/strapi": "4.1.5",
    "pg": "8.7.3",
    "pg-connection-string": "2.5.0",
    "sqlite3": "npm:@vscode/sqlite3@^5.0.8",
    "strapi-plugin-navigation": "2.0.10"
```
```
node : v16.14.0
npm : 8.3.1
```

**Comment by cyp3rius** [comment] 2022-03-30 11:48
@Nabellaleen can you please check what response you're getting as the PUT and if there is nothing in the server logs? Just tested it and works on `2.0.10`

**Comment by cyp3rius** [comment] 2022-03-30 19:49
I've reproduced your case @Nabellaleen.

Such thing happen if you've got Single Type defined but not saved. Try to fill type data and save it (don't need to publish). 

Next version is going to warn you in settings, that because type is not "initialized" you can't use it.

**Comment by cyp3rius** [comment] 2022-03-30 21:42
Should be fixed in `v2.0.12`.

**Comment by Nabellaleen** [comment] 2022-03-31 22:46
Oh yeah, I see ! I'll check that tomorrow and tell you !

Thanks for adding a warning :)

**Comment by Nabellaleen** [comment] 2022-04-01 16:42
It is working !

**Comment by cyp3rius** [comment] 2022-04-01 16:43
Closing then :)

**Closed** 2022-04-01 16:43 UTC
Labels: bug, v4, waiting for feedback
