### ISSUE TITLE
Problem with 2.0.9 pagination and postgresql

### ISSUE THREAD

**Issue by cortopy** [VirtusLab-Open-Source/strapi-plugin-navigation#189] opened 2022-03-28 15:02 UTC
I just tried 2.0.9 and I'm getting this error in the backend logs when I try to access the frontend

```
[2022-03-28 15:53:04.325] error: select "t0".* from "navigations" as "t0" limit $1 - LIMIT must not be negative
error: select "t0".* from "navigations" as "t0" limit $1 - LIMIT must not be negative
    at Parser.parseErrorMessage (/home/cortopy/code/disruptor/cms/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/cortopy/code/disruptor/cms/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/cortopy/code/disruptor/cms/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/cortopy/code/disruptor/cms/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

I'm using PostgreSQL 13

This wasn't happening with earlier versions, so I suspect the problem lies in the changes done in https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/pull/185/files#diff-9ba71205ff2062647c32f47eebb1243330e0e2774f4f49bb26ab84644cb1c52f

**Comment by Kinbaum** [comment] 2022-03-28 17:01
I can confirm this in MySQL 8 as well. I tried upgrading from 2.0.8 to 2.0.9 to resolve issue #182 but after doing so, I get the following error:

```
error: select `t0`.* from `navigations` as `t0` limit -1 - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1' at line 1
@pioneer/strapi:dev: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1' at line 1
```

**Comment by cyp3rius** [comment] 2022-03-28 17:18
Yep, Thats not compatible with v3 approach, do not update to v2.0.9.

I how to take it and fix by night today.

**Comment by cyp3rius** [comment] 2022-03-28 20:56
@cortopy, @Kinbaum `v2.0.10` has been just released. Check please if fixed your issues and close the ticket.

**Comment by Kinbaum** [comment] 2022-03-28 22:28
Hey @cyp3rius I no long receive the error above, but I noticed that when I save a single type, the entity is actually removed. This doesn't happen when using a collection type

<img width="984" alt="Screen Shot 2022-03-28 at 6 17 18 PM" src="https://user-images.githubusercontent.com/6590356/160496376-113c788b-3649-4a5e-88b9-03087fd49d18.png">
 
<img width="1006" alt="Screen Shot 2022-03-28 at 6 18 04 PM" src="https://user-images.githubusercontent.com/6590356/160496470-446930a8-dc45-491a-aefe-9ed4af6c6450.png">

Also, I've enabled permissions for public, but when requesting the navigation through graphql, I receive a `Forbidden access` message

<img width="380" alt="Screen Shot 2022-03-28 at 6 18 55 PM" src="https://user-images.githubusercontent.com/6590356/160496539-7d3d1237-6c73-483c-beae-c57d80e69f19.png">

<img width="776" alt="Screen Shot 2022-03-28 at 6 19 48 PM" src="https://user-images.githubusercontent.com/6590356/160496627-6e671eb0-3353-4e0f-ad88-724e62b8f284.png">

**Comment by cortopy** [comment] 2022-03-29 17:14
2.0.10 it's working for me

**Comment by Kinbaum** [comment] 2022-03-29 17:59
@cortopy Do you have single types with publishing turned on? If so is that working for you?
When I press save, I notice that the `items[]` in the payload is empty:

<img width="746" alt="Screen Shot 2022-03-29 at 1 58 16 PM" src="https://user-images.githubusercontent.com/6590356/160675337-a4b0ce40-72a2-4a40-806b-29da163b9a9e.png">

**Comment by cortopy** [comment] 2022-03-29 18:11
My collection types have publishing on, but not the single types. Haven't tested with single types and publishing on

**Comment by Kinbaum** [comment] 2022-03-29 18:27
Ah ok. Single types won't show up for me unless publishing is turned on, but that doesn't do much good when the item is removed after saving

**Comment by cyp3rius** [comment] 2022-03-29 18:33
@Kinbaum If I get your issue properly the nested items are not saving? Can you validate if all of them are sent to the API?

Will check that end, maybe because of the `limit` property is set to 0 and is not returning values

**Comment by Kinbaum** [comment] 2022-03-29 18:36
@cyp3rius This is a top-level item and for this purpose, I've removed all other items. The entity does not persist after saving

**Comment by cyp3rius** [comment] 2022-03-29 18:42
I've tested it with publishing on and of single and Collection types so that must be something not related directly to this case. Let me dig into that a bit more. Some additional questions which might help me:

1. How many types you have got configured in navigation plugin?
2. Is it happening to all single types you've got?
3. In overall you've got massive amount of entities or not?

Thanks for coop

**Comment by Kinbaum** [comment] 2022-03-29 18:45
Sure thing:

1. I have 3 types configured for this plugin (2 collection, 1 single)
2. I added another single type to test this scenario, this also has the same removal behavior
3. This is a relatively new project with less than 20 entities per collection.

**Comment by cyp3rius** [comment] 2022-03-29 18:57
Thanks a lot for that details. There is also a possibility that MySQL/MariaDB behaves differently than PostgreSQL in term sof ids / global ids as it works for @cortopy but not works for you @Kinbaum and the only diff is DB you selected.

Will keep you posted.

**Comment by cyp3rius** [comment] 2022-03-30 14:00
Made some fixes in `v2.0.11`, hopefully it will resolve your issue @Kinbaum . If not lets setup a screen share to better get the cause.

**Comment by Kinbaum** [comment] 2022-03-30 15:59
Just tried this version out as well and it still isn't working. Also, when clicking on the trashcan and then hitting save, this error displays:

```
error: Cannot destructure property 'id' of 'object null' as it is null.
TypeError: Cannot destructure property 'id' of 'object null' as it is null.
    at /node_modules/strapi-plugin-navigation/server/services/navigation.js:770:64
```

I won't be able to screenshare, but I can provide you more information. I decided to downgrade to test other versions combinations. Here's what I found:

<details>
<summary>Strapi (4.1.3) - Nav (2.0.8)</summary>
<br />
<p>This is the first version that allows you to save a single type from the dialog:</p>

<img width="832" alt="Screen Shot 2022-03-30 at 11 38 01 AM" src="https://user-images.githubusercontent.com/6590356/160874668-2e917805-9618-47f3-9e67-6ec3991b57cc.png">

<p>After saving the dialog, you cannot save the page</p>

<img width="991" alt="Screen Shot 2022-03-30 at 11 39 47 AM" src="https://user-images.githubusercontent.com/6590356/160875066-5216df91-0195-406e-8f32-d754b75b5a0f.png">
</details>

<details>
<summary>Strapi (4.1.3) - Nav (2.0.9)</summary>
<br />
<p>This is the first version that introduces the SQL syntax error</p>

```
error: select `t0`.* from `navigations` as `t0` limit -1 - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1' at line 1
```
</details>

<details>
<summary>Strapi (4.1.3) - Nav (2.0.10 and 2.0.11)</summary>
<br />
<p>This  version allows you to save a single type from the dialog:</p>

<img width="831" alt="Screen Shot 2022-03-30 at 11 49 29 AM" src="https://user-images.githubusercontent.com/6590356/160877066-d974b266-e378-48f0-a1c6-151439ff6a76.png">

<p>After saving the dialog, you are able to save the page</p>

<img width="970" alt="Screen Shot 2022-03-30 at 11 50 22 AM" src="https://user-images.githubusercontent.com/6590356/160877287-4c6815d0-2fef-412b-879f-591569b538e3.png">

<p>After saving the page, the single type entity is removed from</p>

<img width="976" alt="Screen Shot 2022-03-30 at 11 51 19 AM" src="https://user-images.githubusercontent.com/6590356/160877472-c792ec55-c3ca-47a7-bb76-1dfdd2969c81.png">
</details>

I've tested this on all strapi versions, including: 4.1.3 - 4.1.6 and the new 4.2.0 beta.
The last scenario I've outlined behaves the same on all of these version combinations

**Comment by Kinbaum** [comment] 2022-03-30 16:53
Just doing a bit of digging in the navigation service... by the time this is called the related element is undefined:

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/blob/4366fef5edcb6e1adae808b12b33d84a568d72ba/server/services/navigation.js#L320 

I get this as a response in my terminal

```json
{
    "id": 2,
    "name": "Public Navigation",
    "slug": "public-navigation",
    "visible": true,
    "createdAt": "2022-03-28T22:16:29.177Z",
    "updatedAt": "2022-03-28T22:16:31.702Z",
    "items": [
        {
            "id": 17,
            "title": "Home",
            "type": "INTERNAL",
            "path": "/",
            "externalPath": null,
            "uiRouterKey": "home",
            "menuAttached": true,
            "order": 1,
            "createdAt": "2022-03-30T15:57:59.986Z",
            "updatedAt": "2022-03-30T16:37:58.961Z",
            "collapsed": false,
            "parent": null,
            "audience": [],
            "related": undefined,
            "items": []
        }
    ]
}
```

The `payload` just before this has the related item

```json
{
    "id": 2,
    "name": "Public Navigation",
    "visible": true,
    "items": [
        {
            "id": 17,
            "parent": null,
            "master": 2,
            "title": "Home",
            "type": "INTERNAL",
            "updated": true,
            "removed": false,
            "order": 1,
            "uiRouterKey": "home",
            "collapsed": false,
            "menuAttached": true,
            "audience": [],
            "path": "/",
            "related": [
                {
                    "ref": "api::homepage.homepage",
                    "field": "navigation"
                }
            ],
            "items": []
        }
    ]
}
```

**Comment by cyp3rius** [comment] 2022-03-30 17:16
That terminal error says more about the issue. Thanks a lot for digging, will secure that for failing and should work as expected.

**Comment by cyp3rius** [comment] 2022-03-30 21:42
I've fixed error from your latest posts in `v2.0.12` and forced saving Single Types relations with `id: 1` as seems on some MySQL drivers it wasn't working by default.

**Comment by Kinbaum** [comment] 2022-03-30 21:59
@cyp3rius LGTM! Thank you for solving this.

**Comment by cyp3rius** [comment] 2022-03-30 22:01
Jeez, must grab a beer then :) The trickiest case with Strapi I ever had. Closing this one, thanks for cooperation @Kinbaum 👍

**Closed by cyp3rius** 2022-03-30 22:01 UTC
Labels: bug, v4, waiting for feedback
