### ISSUE TITLE
Can't save added items 

### ISSUE THREAD

**Issue by lucaay** [VirtusLab-Open-Source/strapi-plugin-navigation#267] opened 2022-08-19 07:59 UTC
1. Add 1 or more items to UI Navigation
2. Save button stays grayed out.
![image](https://user-images.githubusercontent.com/32814024/185572034-da0dc5d1-6c94-4b8f-a72c-389bdf211e18.png)

TRIED: 
1. Uninstall the plugin and install it again (no effect)
2. Create manual config inside config/plugins.js by following the docs (no effect)

**Comment by ltsNotMike** [comment] 2022-08-19 10:15
Hi @lucaay 
I'm looking into the issue. 
Could you please provide: 
- Strapi version
- Plugin version
- Node version 
- Database type
It will help me with reproducing this bug.

**Comment by lucaay** [comment] 2022-08-19 12:46
Hi @ltsNotMike. The informations you asked for: 
Strapi Version: 4.2.2
Plugin Version: 2.2.1
Node Version: v16.15.1
Database type: sqlite

**Comment by ltsNotMike** [comment] 2022-08-22 06:51
Unfortunately, I wasn't able to reproduce this on my side. I will need some more information 🙂

- Did you start this project on version 2.2.1 of our plugin? 
- Is it possible to provide screens or video of items you are trying to add? 
- Could you provide a screen or snippet of your config?

**Comment by lucaay** [comment] 2022-08-22 10:11
1. Yes, i tried to but i wasn't able to click on save.
2. https://youtu.be/plrd5KsqoM0
3. In config/plugins.js i have nothing related to this plugin 
![image](https://user-images.githubusercontent.com/32814024/185895203-85c98b28-ce1a-4f3e-ab0e-1c9eac35c18f.png)
![image](https://user-images.githubusercontent.com/32814024/185895414-0a4fb7b6-c07a-4230-bbe7-bf3c7fa2460a.png)

**Comment by drazik** [comment] 2022-08-23 08:25
I have the same problem on v2.0.13. In my case, I could create some items when I created the navigation and some items a few days ago. But now the save button is always disabled.

**Comment by ltsNotMike** [comment] 2022-08-24 09:15
In your video @lucaay, you add internal items without providing a related field. This causes the navigation validator to block saving capability.
 
This is still a bug because no error message is provided. I will fix the error display asap, but please verify that you can save navigation with items that have the related field filled. 

@drazik could you also provide a screenshots or video of your problem? This will help me in resolving your issue faster.

**Comment by lucaay** [comment] 2022-08-24 12:32
well, it's working now 🥳. thanks @ltsNotMike !

**Closed** 2022-08-24 12:59 UTC
Labels: bug, v4, waiting for feedback
