### ISSUE TITLE
Error on ui-navigation save.  strapi v4.0.4 ; navigation 2.0.0-beta.3

### ISSUE THREAD

**Issue by kostikovmu** [VirtusLab-Open-Source/strapi-plugin-navigation#139] opened 2022-01-18 07:10 UTC
`my-plugin.886cd737.chunk.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'payload')
    at my-plugin.886cd737.chunk.js:1:8228
    at c (main.2b4fc56d.js:2:2085544)
    at Generator._invoke (main.2b4fc56d.js:2:2085332)
    at Generator.next (main.2b4fc56d.js:2:2085973)
    at t (main.2b4fc56d.js:2:550)
    at u (main.2b4fc56d.js:2:761)`

**Comment by ltsNotMike** [comment] 2022-01-18 09:42
@kostikovmu I could not reproduce this bug. Can you please provide a screenshot of the error and the following data:
- exact scenario you are triggering
- node.js version
- npm version
- operating system

**Comment by thomaseckhardt** [comment] 2022-01-20 14:00
@ltsNotMike I get the same error.

**Steps to reproduce (see video)**
* Create first/new item
* Fill out the fields
  * Title: Test
  * Attach to menu: On
  * Internal Link: Off
  * External Url: https://www.domain.com
* Hit Save
* Hit Save (located at the top of the page)

**Environment**
* Strapi v4.0.4
* Node v14.17
* MacOS 10.15.7

https://user-images.githubusercontent.com/3824117/150351961-a23abc23-8e51-42a6-97cd-8f66a324ff8e.mov

0

**Comment by thomaseckhardt** [comment] 2022-01-20 14:40
I had overlooked that there must be a configuration where at least a CollectionType is defined.

With the [configuration from the documentation](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/tree/feat/strapi-v4-support#configuration) and a collection of type `Page` with a field `title` the error did not occur anymore.

``` js
// config/plugins.js
module.exports = ({ env }) => ({
  navigation: {
    enabled: true,
    config: {
      additionalFields: ["audience"],
      contentTypes: ["api::page.page"],
      contentTypesNameFields: {
        "api::page.page": ["title"],
      },
      allowedLevels: 2,
    },
  },
});
```

**Comment by kostikovmu** [comment] 2022-01-20 14:48
@ltsNotMike 
My steps:

1. install via `yarn add strapi-plugin-navigation@2.0.0-beta.3`
2. add file `config/plugins.js`
```
module.exports = ({ env }) => ({
  // ...
  navigation: {
    enabled: true,
    config: {
      additionalFields: ['audience'],
      contentTypes: ['api::page.page'],
      contentTypesNameFields: {
        'api::page.page': ['title'],
      },
      allowedLevels: 2,
    }
  }
});
```
3. add one item to menu in "ui-navigation"
4. click "save"
5. Have error and "ui-navigation" not opened again.

- nodejs version 14.18.2
- npm version 8.3.0
- os ubuntu 20.04.3

**Comment by ltsNotMike** [comment] 2022-01-21 10:11
@thomaseckhardt Thank you for the detailed description of the bug. It looks like your issue is connected to #135. I've committed a fix for that, but it's not yet in the release.  Please follow mentioned issue for updates on that.

**Comment by ltsNotMike** [comment] 2022-01-21 12:14
@kostikovmu Thank you for the follow-up on the issue. The bug you're experiencing is caused by a lack of version specification of the "uuid" package. This will be fixed in the new release.

**Closed** 2022-01-21 13:15 UTC
Labels: bug, v4
