### ISSUE TITLE
Internationalization issue is not fixed

### ISSUE THREAD

**Issue by oliynykroman** [VirtusLab-Open-Source/strapi-plugin-navigation#396] opened 2023-11-23 12:21 UTC
After previous fix. I had new issue. 
How to reproduce: 
1. Update plugin. 
2. Add new language in  settings > Internationalization
3. Log out, login
4. Add new navigation menu.
5. Prev menu got lost one language and get new All menu items just destroys :( . New menu will get first and last language. Each next menu got strange language relations
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/29798653/95033045-7f09-48fe-9e97-888478b669bc)

As i see the issue is in menu language relations table. Also removed EN language, but on DB i still see deleted locale:
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/29798653/41ccf939-aa41-435b-a5e6-f0de0884ec10)

**Comment by CodeVoyager** [comment] 2023-11-24 12:09
Hi @oliynykroman 
Did you restart strapi server after adding new language version to the Strapi? On server bootstrap these kind of issues should be resolved. If these issues persist after server restart we will need to look deeper into the issue.

We're sorry for your inconvenience.

**Comment by oliynykroman** [comment] 2023-11-27 10:03
Hi @CodeVoyager 
Yes, i did. Also made build. I made short video with issue: 
How to reproduce:

1. Had some menu with two languages versions (for ex. Header)
2. Added new language.
3. Logged out, Restarted server, made build.
4. Logged in admin. See bugs like in video.

Also remove some internationlization doesn't affect locales in DB

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/29798653/043f5ca5-8ffa-4596-93b2-79d875ffa90c

**Comment by CodeVoyager** [comment] 2024-01-20 11:39
Hi @oliynykroman,

Hopefully this will be the last of i18n issues. There's a PR to cover issues mentioned by you. 

FYI: Navigations are not deleted from DB when locale version is disabled in admin panel, by design. We debated that decision and decided that locale version change is easy to made by hard to revert. If anyone needs those items removed it can be easily done by SQL query. We are open for discussion though.

**Comment by cyp3rius** [comment] 2024-02-08 16:38
Released as part of `2.4.0`.

**Closed by cyp3rius** 2024-02-08 16:38 UTC
Labels: bug, solved, v4
