### ISSUE TITLE
Feature Request: provide an option to disable/hide the URL on internal links

### ISSUE THREAD

**Issue by luxterful** [VirtusLab-Open-Source/strapi-plugin-navigation#152] opened 2022-02-09 12:05 UTC
In my strapi setup i have an entity type called "Page" which has an href as required argument. 
With this argument i will render all available pages. 

In my frontend framework (Nuxt): If there is a request i will take the path and search for it in all pages. If no page was found i will trigger an 404.

In this setup i don't need the URL on the Navigation Element because i can get it from the refered entity.
Do you plan to add an option to disable/hide the URL option on internal links?

---
Btw: Thank you so much for this Plugin. Was looking for sth like this a year or so.

**Comment by cyp3rius** [comment] 2022-02-10 07:48
A tricky question @luxterful ;) But it might be considered as an option. If I get you correctly, you would like to:

1.  entirely turn off url creation for your nav items
2. return the url based on related entity or just keep it as part of related field?

**Comment by luxterful** [comment] 2022-02-10 09:50
@cyp3rius yes, both options would work :)

**Comment by mariansimecek** [comment] 2022-04-05 06:20
Hi, 
I really like this plugin. Any chance that you implement this feature? 
I really like the second idea. Same like **title** pulls from related entity.

**Comment by cyp3rius** [comment] 2022-04-05 06:21
@mariansimecek yep, we've got it in our backlog just after the i18n and custom metadata support :)

**Comment by dentalux** [comment] 2022-07-27 21:35
We would also really appreciate this feature! (We would you both options options on our projects, but mostly the second one).
I'm really glad for this plugin, I found it just now, and immediately tried if this feature is available. I hope it will fit our needs, because we tried to create navigations just by Strapi content types and relations in at least three different ways on different projects, and it was painful (and it still is painful for content admins).

I see that i18n is available, I'm not sure about custom metadata and if you are still working on it, but do you have some estimated time of releasing this feature?
Thanks for your work!

**Comment by ltsNotMike** [comment] 2022-07-28 07:31
I'm working this week on testing and finalizing a big bundle of features that will come in version 2.2. I hope that it will be available as a release next week.

**Comment by dmitrysmagin** [comment] 2022-08-05 15:08
I also second that feature.
In case of internal links, collection types usually contain slugs which will form the final url of the page.
That's why having separate url entry field is redundant.
In my project I have to either enter bogus data into url field when I have internal links or hack the package to ignore identical '/' urls.

**Comment by ltsNotMike** [comment] 2022-08-06 11:05
@dmitrysmagin In the latest version of the plugin you should be able to configure field that will be automatically passed as internal path. This way you don't have to care about populating path field.

**Comment by dmitrysmagin** [comment] 2022-08-06 14:00
@ltsNotMike Thanks, you were right.
Though, url and title fields are not filled instantly when you choose Content Type and Entity, but only after you press Save on the form. And more: once those fields are auto-filled, they are not re-filled when you change the Entity, you have to delete them first prior to saving.
Dziękuję za pomoc.

**Comment by maximelebreton** [comment] 2022-11-08 09:34
Hello @ltsNotMike, and thanks for your plugin!

But same problem here, I configured the plugin to populate `Title` as **Name** field, and `Slug` as **Path** field, and it doesn't populate the fields when the entity is selected, and when I try to save, I can't because the **URL** field is required...

The excepted behaviour is if you choose to populate the **Name** and **Path** fields, when you create a new internal menu item, and select an entity, it should be populate the `Title` in the **Title** field, and `Slug` in the **URL** field.
​
![image](https://user-images.githubusercontent.com/1072425/200523162-5e32a269-3f2c-453b-b980-8509d09d4905.png)

![image](https://user-images.githubusercontent.com/1072425/200528643-e68650c2-3588-4a7d-b2c8-c401b91fcedb.png)

And last little UX suggestion: maybe there is an inconsistency between the names of the input fields in **General settings** and the **New navigation item**? Maybe this would be more consistency:  `Title` → `Name`, and  ​`URL` → `Path` (or the opposite)

Thanks!

**Comment by ltsNotMike** [comment] 2022-11-08 16:40
Hi @maximelebreton,
Nice to hear that you enjoy the plugin. I will try to improve this feature when I'll find some time. Could you describe the steps to reproduce this behavior in other words? I'm not sure I understand the _before and after configuration_.

**Comment by cyp3rius** [comment] 2024-02-08 16:38
Released as part of `2.4.0`.

**Closed by cyp3rius** 2024-02-08 16:38 UTC
Labels: enhancement, question, solved, discussion

**Comment by Alexnortung** [comment] 2024-05-13 12:28
I am not sure where to find the option to disable/hide the url field? Is it in settings?

Also I don't see that the field can be hidden in [the code for the component](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/blob/4d21bfbbcb48c15dc3c607ad0636446c911e4a27/admin/src/pages/View/components/NavigationItemForm/index.tsx#L531-L543).

Did you actually implement this? Or is there some hidden thing you need to do to achieve the desired effect of mentioned in this issue?

**Comment by Alexnortung** [comment] 2024-05-21 10:49
Can this issue be reopened? @cyp3rius @CodeVoyager
