### ISSUE TITLE
Issue With saving Menu

### ISSUE THREAD

**Issue by mattmillen888** [VirtusLab-Open-Source/strapi-plugin-navigation#249] opened 2022-07-15 06:47 UTC
Im having an issue where i create the first menu and save which is fine. then i create a nested item and save then it disappears. but when i look in the database it has saved it?

Any ideas why this might be? only i cant use the plugin right now with this behaviour. 

Below are my versions:
node v14.19.1
npm 6.14.13
postgresSql 13

Dependencies
    "@_sh/strapi-plugin-ckeditor": "^1.1.0",
    "@strapi/plugin-graphql": "^4.2.3",
    "@strapi/plugin-i18n": "^4.2.3",
    "@strapi/plugin-sentry": "^4.2.3",
    "@strapi/plugin-seo": "^1.7.4",
    "@strapi/plugin-users-permissions": "^4.2.3",
    "@strapi/provider-upload-cloudinary": "^4.2.3",
    "@strapi/strapi": "^4.2.3",
    "pg": "^8.7.3",
    "pg-connection-string": "^2.5.0",
    "strapi-plugin-navigation": "^2.1.0",
    "strapi-plugin-placeholder": "^4.1.7",
    "strapi-plugin-sitemap": "^2.0.8",

Any help greatly appreciated. I have also attached a video of what's happening. plus proof that it saved to the database but won't show in frontend admin UI

https://user-images.githubusercontent.com/25214970/179167209-a1894c59-a8e8-4f06-96fb-732901ea21bb.mov

![Screen Shot 2022-07-15 at 15 11 29](https://user-images.githubusercontent.com/25214970/179167265-363cd73a-1722-4970-9876-dd2c8843849c.png)

**Comment by mattmillen888** [comment] 2022-07-16 23:44
• We are not receiving any errors
• I deleted the menus and tried again. here are the screen shots

<img width="1335" alt="navigation_items" src="https://user-images.githubusercontent.com/25214970/179330880-c8d7c6b1-ded4-4aa0-9773-2c2626d91647.png">

<img width="363" alt="navigations_items_master_links" src="https://user-images.githubusercontent.com/25214970/179331565-b2e041ba-49c5-4ebd-ad76-cd8f058a37a0.png">

<img width="275" alt="navigations_items_parent_links" src="https://user-images.githubusercontent.com/25214970/179331595-ea89fad2-28d8-4558-9771-9d7461c0f94f.png">
 
• Yes it only happens with nested items NOT on top level menus
•It makes no difference if the menu is a wrapper/internal/external

What is interesting is that if i delete the main top level menu and save then the nested item thats in the database appears. please see below.

https://user-images.githubusercontent.com/25214970/179335435-16f8f69c-2571-428c-83e5-cda1470a75e5.mov

It seems to be also happening in SQlite

**Comment by mattmillen888** [comment] 2022-07-17 00:27
Whats interesting is I just completely created a new database from scratch using postgres and its not happening now. very strange

**Comment by ltsNotMike** [comment] 2022-07-18 06:39
It looks like it was some kind of faulty database. I will assume that it was related only to the database issue and close this for now. If you ever happen to reproduce this bug again please feel free to reopen it 🙂.

**Closed by ltsNotMike** 2022-07-18 06:39 UTC
Labels: bug, investigation, v4

**Comment by rimallo** [comment] 2022-08-17 10:34
I am having similar issue with v4.3.2 and mysql.

1. Choosing menu to edit (right top). 
2. Creating first item. 
3. Save. 
4. Creating nested item. Click save in modal.
5. Save on the top right near chosen menu - disabled.
6. Reloading page - no saved items.

Console clean.

**Comment by rimallo** [comment] 2022-08-17 10:39
... tried to re-enable the topmost save button in console - no luck. looks like it has no click listeners binded to it.

**Comment by ltsNotMike** [comment] 2022-08-17 12:30
Hi @rimallo.
This seems to be unrelated to the issue matt was having. I will look into your issue asap. 
Could you please provide the plugin version that you are running?
